# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=30)),
                ('reminder', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('queue', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('parent', models.CharField(max_length=10)),
                ('related', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('start', models.CharField(max_length=30)),
                ('deadline', models.CharField(max_length=30)),
                ('reminder', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
                ('key', models.CharField(max_length=10)),
                ('creating_time', models.CharField(max_length=30)),
                ('editing_time', models.CharField(max_length=30)),
            ],
        ),
    ]
