# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='failed_tasks',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='queue',
            name='opened_tasks',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='queue',
            name='solved_tasks',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='task',
            name='sub_tasks',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='reminder',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.TextField(default=None),
        ),
    ]
