# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0002_auto_20180903_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='reminder',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.TextField(default=''),
        ),
    ]
