# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0004_auto_20180903_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name=0)),
                ('nick', models.CharField(max_length=100)),
                ('queues', models.TextField(default='[]')),
                ('tasks_author', models.TextField(default='[]')),
                ('tasks_responsible', models.TextField(default='[]')),
                ('notifications', models.TextField(default='[]')),
                ('new_messages', models.TextField(default='[]')),
            ],
        ),
    ]
