# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=10),
        ),
    ]
