# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0006_auto_20180903_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='owner',
            field=models.IntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
