# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0007_auto_20180903_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='queues',
        ),
        migrations.AddField(
            model_name='user',
            name='_queues',
            field=models.TextField(default='[]'),
        ),
    ]
