# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0008_auto_20180904_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_queues',
            new_name='queues',
        ),
    ]
