# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0009_auto_20180904_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='failed_tasks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='queue',
            name='opened_tasks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='queue',
            name='solved_tasks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_messages',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='notifications',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='queues',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='tasks_author',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='tasks_responsible',
            field=models.TextField(default=''),
        ),
    ]
