# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0010_auto_20180904_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='period',
            field=models.CharField(default='', max_length=20),
        ),
    ]
