# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import web_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0013_auto_20180905_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.TextField(default='', help_text='Use format: frequency:time, where frequency - every_day, every_week, or day of week', validators=[web_tracker.validators.validate_reminder]),
        ),
    ]
