# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import web_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0014_auto_20180905_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='queue',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.TextField(default='', validators=[web_tracker.validators.validate_reminder]),
        ),
    ]
