# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import web_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0016_auto_20180905_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='name',
            field=models.CharField(max_length=100, validators=[web_tracker.validators.validate_queue_name]),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
