# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 14:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0017_auto_20180905_1701'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
