# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0018_auto_20180906_1715'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
