# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import web_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0021_auto_20180906_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='reminder',
            field=models.TextField(default='', validators=[web_tracker.validators.validate_reminder]),
        ),
    ]
