# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import web_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0022_auto_20180906_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.CharField(max_length=30, validators=[web_tracker.validators.validate_deadline]),
        ),
    ]
