# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import web_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web_tracker', '0023_auto_20180907_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='related',
            field=models.CharField(max_length=30, validators=[web_tracker.validators.validate_related]),
        ),
    ]
